[build]
  base = "frontend"
  command = "npm install --prefix .. && npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  included_files = ["../node_modules/**"]

[dev]
  command = "npm run dev"
  framework = "#custom"
  targetPort = 5173
  port = 8888